Parallelism support
spacemeshos/post pull request #13
Opened 2019-05-20 11:10 UTC by moshababo

Adding parallelism support, based on https://github.com/spacemeshos/post/pull/12.

Number of workers (goroutines) is: `min(num of cpus, num of files)`.
Number of files is not adjusted yet. Used only in tests.

Basic _initialization_ benchmarks:
````
1.1GB space
32 files
12 CPUs (6 physical)

no parallelism: 235 sec
no parallelism 1 file: 243 sec
parallel: workers as num of files (32): 64 sec
parallel: workers as num of cpus (12): 63 sec
````
````
2.2GB space
32 files
12 CPUs (6 physical)

no parallelism:  476 sec
no parallelism 1 file: 501 sec
parallel: workers as num of files (32): 128 sec
parallel: workers as num of cpus (12): 131 sec
parallel: workers as num of cpus / 2 (6): 137 sec
parallel: workers as num of cpus / 4 (3): 210 sec
````

2019-05-20 11:17 UTC, moshababo commented
`GOMAXPROCS` will be set after implementing https://github.com/spacemeshos/go-spacemesh/issues/907.

2019-05-24 18:37 UTC, zalmen requested changes

2019-05-24 18:37 UTC, zalmen commented on initialization/initialize.go
> +		numOfWorkers = min(runtime.NumCPU(), numOfChunks)
`runtime.NumCPU` gives you the number of logical cores, I think the relevant number should be the number of physical cores as the work is cpu intensive. What do you think?
Also, not sure why, but when I run `runtime.NumCPU` on my mac I get 1, what am I missing?

2019-05-24 18:37 UTC, zalmen commented on initialization/initialize.go
> +func Initialize(id []byte, space uint64, numOfProvenLabels uint8, difficulty proving.Difficulty, parallel bool) (*proving.Proof, error) {
I know it is not part of this PR, but I think that instead of passing the space size we should provide the number of units where the size of the unit is configurable

2019-05-24 18:37 UTC, zalmen commented on initialization/initialize.go
> +	return initialize(id, space, space, numOfProvenLabels, difficulty, parallel)
I don't understand the `filesize` param and why it is set to `space`

2019-05-24 18:37 UTC, zalmen commented on initialization/initialize.go
> +			return nil, err
We need to have a proper teardown in case of failure, we shouldn't leave stale init files

2019-05-26 12:16 UTC, moshababo commented on initialization/initialize.go
> +		numOfWorkers = min(runtime.NumCPU(), numOfChunks)
Although it make sense, I’d rather do better benchmarking first.

2019-05-26 12:25 UTC, moshababo commented on initialization/initialize.go
> +func Initialize(id []byte, space uint64, numOfProvenLabels uint8, difficulty proving.Difficulty, parallel bool) (*proving.Proof, error) {
I wanted to do this also to `numOfProvenLabels`, by keeping these params only in a private function which is needed for testing (same as `filesize`). It wasn’t straight forward due to some dependencies. 

In the end we’ll expose only what we want the client to dynamically control.

2019-05-26 12:29 UTC, moshababo commented on initialization/initialize.go
> +	return initialize(id, space, space, numOfProvenLabels, difficulty, parallel)
As mentioned above, having `filesize` as a param is needed for testing. 
I thought not to expose `filesize` to the client, so it’s not a param for the public function.
In addition, I didn’t want to deal with the `filesize` calculation logic right now, so i’m merely using `space`, and there will be only 1 file (I can also use `numOfFiles` instead).

2019-05-26 12:36 UTC, moshababo commented on initialization/initialize.go
> +			return nil, err
I'll deal with the teardown in my other PR - don't want to create additional merge problems.

2019-05-26 12:43 UTC, moshababo commented on initialization/initialize.go
> +	return initialize(id, space, space, numOfProvenLabels, difficulty, parallel)
If we'll want this package to be consumed directly by the client (the fullnode) and also by `rpc` package, it's a bit more problematic, and the best would probably be to have an initialization instance which contains config.

2019-05-26 12:59 UTC, zalmen commented on initialization/initialize.go
> +		numOfWorkers = min(runtime.NumCPU(), numOfChunks)
NP, it is best to have the level of concurrency from the configuration

2019-05-26 13:09 UTC, zalmen approved these changes

2019-05-26 13:42 UTC, merged